### ISSUE TITLE
Compiler Issue / undefined symbol [XC8]

### ISSUE THREAD

**Issue by pkerspe** [mondul/fatfs_pic18#1]
First of all let me say: awesome to have this project and give newbies a got starting point for XC8 in combination with fatfs, I was so happy to find this porject!

Unfortunately I have an issue with the code.

When follwoing your video tutorial step by step (even chose the exact same PIC model), I have an issue compiling the project.
`:0: error: (499) undefined symbol:
    _SPI_Open(dist/default/production/Test.X.production.obj)`

I am using the following IDE and Compiler Verisons:
Product Version: MPLAB X IDE v3.30
Java: 1.8.0_65; Java HotSpot(TM) 64-Bit Server VM 25.65-b01
Runtime: Java(TM) SE Runtime Environment 1.8.0_65-b17
System: Mac OS X version 10.11.4 running on x86_64; UTF-8; en_EN

XC-8 Compiler in Verison 1.37

In the Tutorial was one step which I could not do, which is the part where you change the SPI Port to be used to 0, since this line does not exist in the diskio.c file in the git repo.

Any ideas how to fix this issue?

Here is the full stack:
`make -f nbproject/Makefile-default.mk SUBPROJECTS= .build-conf
make[1]: Entering directory '/Users/someuser/MPLABXProjects/Test.X'
make  -f nbproject/Makefile-default.mk dist/default/production/Test.X.production.hex
make[2]: Entering directory '/Users/someuser/MPLABXProjects/Test.X'
"/Applications/microchip/xc8/v1.37/bin/xc8"  --chip=18F25K20 -G -mdist/default/production/Test.X.production.map  --double=24 --float=24 --emi=wordwrite --opt=default,+asm,+asmfile,-speed,+space,-debug --addrqual=ignore --mode=free -P -N255 --warn=-3 --asmlist --summary=default,-psect,-class,+mem,-hex,-file --output=default,-inhx032 --runtime=default,+clear,+init,-keep,-no_startup,-download,+config,+clib,-plib --output=-mcof,+elf:multilocs --stack=compiled:auto:auto:auto "--errformat=%f:%l: error: (%n) %s" "--warnformat=%f:%l: warning: (%n) %s" "--msgformat=%f:%l: advisory: (%n) %s"      --memorysummary dist/default/production/memoryfile.xml -odist/default/production/Test.X.production.elf  build/default/production/mcc_generated_files/spi.p1 build/default/production/mcc_generated_files/mcc.p1 build/default/production/mcc_generated_files/pin_manager.p1 build/default/production/main.p1 build/default/production/_ext/1307105986/diskio.p1 build/default/production/_ext/1307105986/ff.p1  
Microchip MPLAB XC8 C Compiler (Free Mode) V1.37
Build date: Mar 10 2016
Part Support Version: 1.37
Copyright (C) 2016 Microchip Technology Inc.
License type: Node Configuration

:: advisory: (1233) Employing 18F25K20 errata work-arounds:
:: advisory: (1234)  \* No stopping on H/W breakpoints after NOP2
:: warning: (1273) Omniscient Code Generation not available in Free mode
mcc_generated_files/spi.c:91: warning: (520) function "_SPI_Exchange8bitBuffer" is never called
mcc_generated_files/spi.c:130: warning: (520) function "_SPI_IsBufferFull" is never called
mcc_generated_files/spi.c:135: warning: (520) function "_SPI_HasWriteCollisionOccured" is never called
mcc_generated_files/spi.c:140: warning: (520) function "_SPI_ClearWriteCollisionStatus" is never called
mcc_generated_files/pin_manager.c:68: warning: (520) function "_PIN_MANAGER_IOC" is never called
/Users/someuser/MPLABXProjects/Test.X/ff.c:2590: warning: (520) function "_f_read" is never called
mcc_generated_files/spi.c:107: warning: (1498) pointer (SPI_Exchange8bitBuffer@dataOut) in expression may have no targets
mcc_generated_files/spi.c:119: warning: (1498) pointer (SPI_Exchange8bitBuffer@dataOut) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/diskio.c:219: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:220: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:221: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:222: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:223: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:332: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:353: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:395: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:434: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:484: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:486: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:497: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/diskio.c:505: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:528: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:836: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:846: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:852: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:890: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:894: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:899: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:906: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:907: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:914: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:1257: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:1258: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2029: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2130: warning: (759) expression generates no code
/Users/someuser/MPLABXProjects/Test.X/ff.c:2243: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2265: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2233: warning: (759) expression generates no code
/Users/someuser/MPLABXProjects/Test.X/ff.c:2247: warning: (759) expression generates no code
/Users/someuser/MPLABXProjects/Test.X/ff.c:2266: warning: (759) expression generates no code
/Users/someuser/MPLABXProjects/Test.X/ff.c:2474: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2505: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2612: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2617: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2645: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2669: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2674: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2603: warning: (1498) pointer (f_read@br) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2629: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2630: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2631: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2634: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2641: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2667: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2673: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2615: warning: (1498) pointer (f_read@fp) in expression may have no targets
/Users/someuser/MPLABXProjects/Test.X/ff.c:2718: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2760: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2787: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2792: warning: (752) conversion to shorter data type
/Users/someuser/MPLABXProjects/Test.X/ff.c:2842: warning: (752) conversion to shorter data type
:0: error: (499) undefined symbol:
    _SPI_Open(dist/default/production/Test.X.production.obj) 
(908) exit status = 1
nbproject/Makefile-default.mk:205: recipe for target 'dist/default/production/Test.X.production.hex' failed
make[2]: Leaving directory '/Users/someuser/MPLABXProjects/Test.X'
nbproject/Makefile-default.mk:84: recipe for target '.build-conf' failed
make[1]: Leaving directory '/Users/someuser/MPLABXProjects/Test.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make[2]: **\* [dist/default/production/Test.X.production.hex] Error 1
make[1]: **\* [.build-conf] Error 2
make: **\* [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 9s)`

**Comment by pkerspe** [comment]
Just found the definition of "_SD_SPI" has been moved to diskio.h and is already set to 0. So this should not be the cause for the compiler Problems.

**Comment by MarwenAouini** [comment]
I am contacting you to ask for your help.

I am trying to develop SPI mode communication between SD card and PIC18F47J13, This PIC is not supported by MCC. I used MPLAB X IDE in  version 3.35 and XC-8 Compiler in verison 1.37.

I have already used a library of the FatFs, but I was unable to initialize and communicate with SD.

the program compiles and runs on physical but when using the library FatFs the program crashes. This is what I'm doing, with the warnings

Please can you help me. thank you in advance.
